
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
            <head>
        <title>World Elephant Day 2024</title>
        <link rel="stylesheet" href="https://use.typekit.net/keh3fmz.css" />
      </head>
      <body>{children}</body>
    </html>
  );
}


